version: '3'

# We will use AWS services for postgres (AWS RDS) and redis (AWS Elastic Cache) in PROD.
#
# The service names are use as 'hostname' for the running containers.
services:
  nginx:
    image: "roelfie/fibonacci-nginx"
#    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    # If you run into "connect() failed (111: Connection refused) while connecting to upstream" try the following:
#    depends_on:
#      - api
#      - client
  api:
    # The server project was configured to listen on port 5000 (see index.js)
    image: "roelfie/fibonacci-api"
#    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    # By default, this 'Create React App' runs on port 3000
    image: "roelfie/fibonacci-client"
#    mem_limit: 128m
    hostname: client
  worker:
    image: "roelfie/fibonacci-worker"
#    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

